_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 8

# defautls amp_backend="native"  apex is mixed presition culculation nvidia provide
amp_backend: "apex"

# defautls amp_backend="native"  apex is mixed presition culculation nvidia provide
amp_backend: "apex"

resume_from_checkpoint: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
