name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build -f .devcontainer/Dockerfile . --tag my-image-name
          docker run -dit my-image-name python /workspace/project/run.py mode=debug
